### ISSUE TITLE
MemorySanitizer: SEGV on unknown address 0x006000000000 The signal is caused by a WRITE memory access when seed=1614745901343499

### ISSUE THREAD

**Issue by yansendao** [csmith-project/csmith#114]
```bash
yansendao@jvmtest-129:csmith$ ./install-0bd545feec35013caa8fa8732f12f8da28fa35be/bin/csmith -s 1614745901343499 -o test.c       
yansendao@jvmtest-129:csmith$ clang -fsanitize=memory -O0 -I /home/yansendao/software/csmith/include/csmith-2.4.0 test.c -w && ./a.out
MemorySanitizer:DEADLYSIGNAL
==46812==ERROR: MemorySanitizer: SEGV on unknown address 0x006000000000 (pc 0xaaaac1b12dd4 bp 0xffffcba33690 sp 0xffffcba31760 T46812)
==46812==The signal is caused by a WRITE memory access.
    #0 0xaaaac1b12dd4 in func_1 (/home/yansendao/opensource/csmith/a.out+0xa3dd4)
    #1 0xaaaac1b05088 in main (/home/yansendao/opensource/csmith/a.out+0x96088)
    #2 0xffff9fa4571c in __libc_start_main /build/glibc-D9JkfM/glibc-2.27/csu/../csu/libc-start.c:310
    #3 0xaaaac1a92d90 in _start (/home/yansendao/opensource/csmith/a.out+0x23d90)

MemorySanitizer can not provide additional info.
SUMMARY: MemorySanitizer: SEGV (/home/yansendao/opensource/csmith/a.out+0xa3dd4) in func_1
==46812==ABORTING


yansendao@jvmtest-129:csmith$ ./install-0bd545feec35013caa8fa8732f12f8da28fa35be/bin/csmith -v
csmith 2.4.0
Git version: 0bd545f
```

[test.zip](https://github.com/csmith-project/csmith/files/5910992/test.zip)

**Comment by yansendao** [comment]
```gdb
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/yansendao/opensource/csmith/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Breakpoint 1, func_1 () at test.c:291
291         int32_t *l_2[10] = {&g_3,&g_3,&g_3,&g_3,&g_3,&g_3,&g_3,&g_3,&g_3,&g_3};
(gdb) c
Continuing.

Breakpoint 2, func_1 () at test.c:312
312         if ((((*l_10) = (-7L)) , g_7))
(gdb) c
Continuing.

Breakpoint 2, func_1 () at test.c:312
312         if ((((*l_10) = (-7L)) , g_7))
(gdb) c
Continuing.

Breakpoint 2, func_1 () at test.c:312
312         if ((((*l_10) = (-7L)) , g_7))
(gdb) p l_10
$11 = (int64_t *) 0x0
```

**Comment by jxyang** [comment]
Might be fixed by https://github.com/csmith-project/csmith/commit/0f934644eb707e3cdf332ab7aebb163ec36bbb31.

Feel free to reopen if you need encounter the bug with the latest commit(s).
