### ISSUE TITLE
global-buffer-overflow when seed = 2680938544

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [csmith-project/csmith#116]
```bash
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ csmith --version  
csmith 2.4.0
Git version: 0f93464

$ csmith --function-attributes --type-attributes --label-attributes --variable-attributes --compiler-attributes --int128 --uint128 --binary-constant --seed 2680938544 > test.c

$ gcc -fsanitize=address -fno-omit-frame-pointer test.c

$ ./a.out
=================================================================
==38443==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555f5ab390be at pc 0x555f5a91292d bp 0x7ffc6a5a7d40 sp 0x7ffc6a5a7d30
READ of size 2 at 0x555f5ab390be thread T0
    #0 0x555f5a91292c in func_53 (/root/a.out+0xd92c)
    #1 0x555f5a926f38 in func_22 (/root/a.out+0x21f38)
    #2 0x555f5a91f443 in func_1 (/root/a.out+0x1a443)
    #3 0x555f5a91dbb7 in main (/root/a.out+0x18bb7)
    #4 0x7f231f91eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #5 0x555f5a912d79 in _start (/root/a.out+0xdd79)

0x555f5ab390be is located 58 bytes to the right of global variable 'crc32_context' defined in 'csmith.h:48:17' (0x555f5ab39080) of size 4
0x555f5ab390be is located 2 bytes to the left of global variable 'g_2' defined in 'test.c:17:16' (0x555f5ab390c0) of size 72
SUMMARY: AddressSanitizer: global-buffer-overflow (/root/a.out+0xd92c) in func_53
Shadow bytes around the buggy address:
  0x0aac6b55f1c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aac6b55f1d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aac6b55f1e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aac6b55f1f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aac6b55f200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0aac6b55f210: 04 f9 f9 f9 f9 f9 f9[f9]00 00 00 00 00 00 00 00
  0x0aac6b55f220: 00 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0aac6b55f230: 00 00 00 00 04 f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9
  0x0aac6b55f240: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x0aac6b55f250: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x0aac6b55f260: f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==38443==ABORTING
```

**Comment by jxyang** [comment]
Seems to be another uint128 problem. 

Fixed with https://github.com/csmith-project/csmith/commit/deddca60d146c692e0ec5e4e345c466bbb3594b1
