### ISSUE TITLE
testcase generate with "csmith --float -s 8642168180452144185" ASAN compalint MemorySanitizer: use-of-uninitialized-value 

### ISSUE THREAD

**Issue by yansendao** [csmith-project/csmith#135]
### test command:

```bash
clang -w -O0 -fsanitize=memory -I ~/software/csmith/include test.c -g3 && ./a.out
```

### result:

```
==132==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xaaaabb843ac4 in func_48 /home1/yansendao/history/issue/boole-issue1968/test.c:1136:9
    #1 0xaaaabb83e878 in func_39 /home1/yansendao/history/issue/boole-issue1968/test.c:882:42
    #2 0xaaaabb839900 in func_20 /home1/yansendao/history/issue/boole-issue1968/test.c:769:16
    #3 0xaaaabb82c5cc in func_2 /home1/yansendao/history/issue/boole-issue1968/test.c:227:115
    #4 0xaaaabb82be2c in func_1 /home1/yansendao/history/issue/boole-issue1968/test.c:208:17
    #5 0xaaaabb824fb8 in main /home1/yansendao/history/issue/boole-issue1968/test.c:1394:5
    #6 0xffffbc25108c in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2408c)
    #7 0xaaaabb7b2dd0 in _start (/home1/yansendao/history/issue/boole-issue1968/a.out+0x27dd0)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home1/yansendao/history/issue/boole-issue1968/test.c:1136:9 in func_48
Exiting
```

**Comment by yansendao** [comment]
creduce result:

 ```c
int main() {
  int a = 0xFBCDA4Fp69;
  if (a)
    ;
}
```


![image](https://user-images.githubusercontent.com/36258307/116058973-f6352680-a6b2-11eb-8788-7f1eb611af95.png)
